apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: jfolger1/backstage
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  dependsOn: ['component: backstage']
  apiConsumedBy: ['component:SBapp1']
